name: Build The Game For Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build The Game For Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
        sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

    - name: Compiling time!
      run: |
        git clone --depth 1 https://github.com/raysan5/raylib.git raylib
        cd raylib/src/
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install
        cd ../../ # Go back to the root directory
        wget https://raw.githubusercontent.com/mastergive514/Untitled-Game/master/main.c
        gcc main.c -o UntitledGame -O1 -Wall -std=c99 -Wno-missing-braces -lraylib -lm -lpthread -ldl -lrt -lX11 -lGL -lGLU
        mkdir output
        cp UntitledGame output/

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Untitled-Game
        path: output/
